#!/bin/bash
set -eux
set -o pipefail

source /root/stackrc

physical_network={{ pillar['quantum']['physical_network'] }}
fixed_range={{ pillar['quantum']['fixed_range'] }}
ovs_range={{ pillar['quantum']['ovs_range'] }}

ovs_address=$(python -c 'import netaddr, sys; print netaddr.IPNetwork(sys.argv[1])[1]' $ovs_range)
ovs_netmask=$(python -c 'import netaddr, sys; print netaddr.IPNetwork(sys.argv[1]).netmask' $ovs_range)

network_gateway=$(python -c 'import netaddr, sys; print netaddr.IPNetwork(sys.argv[1])[1]' $fixed_range)
ovs_fixed_address=${network_gateway}/${fixed_range##*/}

fixed_range_start=$(python -c 'import netaddr, sys; print netaddr.IPNetwork(sys.argv[1])[2]' $fixed_range)
fixed_range_end=$(python -c 'import netaddr, sys; print netaddr.IPNetwork(sys.argv[1])[-2]' $fixed_range)
allocation_pool="start=${fixed_range_start},end=${fixed_range_end}"


# TODO: make default networks configurable via pillar.
# TODO: make this part idempotent.

tenant_id=$(keystone tenant-list | grep ' admin ' | awk '{print $2}')

net_id=$(quantum net-create int --tenant_id $tenant_id --provider:network_type gre --provider:segmentation_id 256 | grep ' id ' | awk '{print $4}')
subnet_id=$(quantum subnet-create --tenant_id $tenant_id --ip_version 4 ${allocation_pool:+--allocation-pool $allocation_pool} --gateway $network_gateway $net_id $fixed_range | grep ' id ' | awk '{print $4}')
