#!/bin/bash
set -e

db_pass={{ pillar['secrets']['db_password'] }}

function grant_access {
  local sql="
    grant all on $1.* to '$2'@'*'         identified by '$3';
    grant all on $1.* to '$2'@'localhost' identified by '$3';
    grant all on $1.* to '$2'@'%'         identified by '$3';
    flush privileges;"
  echo "$sql" | mysql
}

grant_access keystone keystone $db_pass
keystone-manage db_sync

grant_access glance glance $db_pass
glance-manage db_sync

grant_access nova nova $db_pass
nova-manage db sync

grant_access quantum quantum $db_pass

echo
echo "YAY !"
echo
