#!/bin/bash
set -e

if [ $# -ne 1 ]; then
  echo "usage: init-db DB_PASS"
  exit 1
fi

db_pass=$1

function grant_access {
  local sql="
    grant all on $1.* to '$2'@'*'         identified by '$3';
    grant all on $1.* to '$2'@'localhost' identified by '$3';
    grant all on $1.* to '$2'@'%'         identified by '$3';
    flush privileges;"
  echo "$sql" | mysql
}

grant_access keystone keystone $db_pass
keystone-manage db_sync

grant_access glance glance $db_pass
glance-manage db_sync

grant_access nova nova $db_pass
nova-manage db sync

echo "abcdefg"
uptime
echo $0
